"""Local, application-owned retrieval contracts and implementation."""

from .contracts import (
    CHUNKING_POLICY_VERSION,
    CORPUS_SCHEMA_VERSION,
    CorpusChunk,
    CorpusDocument,
    CorpusIngestionResult,
    CorpusManifest,
    CorpusSource,
    CorpusValidationIssue,
    CorpusValidationReport,
    EmbeddingProvider,
    EmbeddingRequest,
    EmbeddingResponse,
    INDEX_SCHEMA_VERSION,
    IndexBuildReport,
    IndexMetadata,
    KnowledgeContext,
    KnowledgeHit,
    SufficiencyDiagnostics,
)
from .corpus import (
    CorpusChunker,
    CorpusNormalizer,
    CorpusPackage,
    CorpusValidationError,
    ingest_corpus,
    validate_corpus_package,
)
from .builder import build_and_publish_index
from .evaluation import (
    EVALUATION_SCHEMA_VERSION,
    EvaluationCase,
    EvaluationCaseResult,
    EvaluationReport,
    EvaluationSuite,
    evaluate_suite,
    load_evaluation_suite,
)
from .index import DeterministicEmbeddingBackend, LocalKnowledgeIndex, load_corpus
from .query_builder import KnowledgeQuery, KnowledgeQueryBuilder

__all__ = [
    "CHUNKING_POLICY_VERSION",
    "CORPUS_SCHEMA_VERSION",
    "CorpusChunk",
    "CorpusChunker",
    "CorpusDocument",
    "CorpusIngestionResult",
    "CorpusManifest",
    "CorpusNormalizer",
    "CorpusPackage",
    "CorpusSource",
    "CorpusValidationError",
    "CorpusValidationIssue",
    "CorpusValidationReport",
    "EmbeddingProvider",
    "EmbeddingRequest",
    "EmbeddingResponse",
    "EVALUATION_SCHEMA_VERSION",
    "EvaluationCase",
    "EvaluationCaseResult",
    "EvaluationReport",
    "EvaluationSuite",
    "INDEX_SCHEMA_VERSION",
    "IndexBuildReport",
    "IndexMetadata",
    "KnowledgeContext",
    "KnowledgeHit",
    "SufficiencyDiagnostics",
    "DeterministicEmbeddingBackend",
    "LocalKnowledgeIndex",
    "KnowledgeQuery",
    "KnowledgeQueryBuilder",
    "load_corpus",
    "ingest_corpus",
    "validate_corpus_package",
    "build_and_publish_index",
    "evaluate_suite",
    "load_evaluation_suite",
]
